// Generated by Laravel Wayfinder in the host application. Must stay ambient
// (no imports/exports in this file) so the module resolves during type checks.
declare module '@/routes/permissions' {
    export const check: {
        url: () => string;
    };
}
